/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.10 5.glb --transform 
Files: 5.glb [4.54MB] > 5-transformed.glb [1.47MB] (68%)
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/5-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Tile_1006.geometry} material={materials.Material_0} />
    </group>
  )
}

useGLTF.preload('/5-transformed.glb')
