/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.10 1.glb --transform
Files: 1.glb [4.54MB] > 1-transformed.glb [1.47MB] (68%)
*/

import React, { useRef, useEffect } from "react";
import { useGLTF } from "@react-three/drei";
import * as THREE from "three";

export function Area({ showModel, path, crackParam, title }) {
	const { nodes, materials } = useGLTF(path);
	useEffect(() => {
		console.log("threejs:", nodes[title]);
	}, []);
	return (
		<group dispose={null}>
			<mesh
				onClick={() => showModel(crackParam)}
				geometry={nodes[title].geometry}
				material={materials.Material_0}
			>
				<meshPhongMaterial color={new THREE.Color(0xeeeeee)} shininess={0} />
			</mesh>
		</group>
	);
}
